### ISSUE TITLE
程序报错是不是我本地环境的问题？

### ISSUE THREAD

**Issue by svolence** [AlloyTeam/Rosin#1]
图片一直上传失败，只好先放在百度了！这是出错信息
http://xiangce.baidu.com/picture/detail/48f75813c59608d8cb01efe1c4782f2eeccf9e06?from=dialog

**Comment by websiteflash** [comment]
@svolence 看不见图片，提示图片正在审核中

**Comment by websiteflash** [comment]
@svolence 能把你的fiddler版本和系统版本发一下吗

**Comment by biqing** [comment]
fiddler是否有安装JsonViewer插件？

**Comment by svolence** [comment]
@websiteflash fiddler4 系统win7 64 位
![1](https://cloud.githubusercontent.com/assets/4159479/6957116/5c1390d4-d92a-11e4-8993-d4799994ff2a.png)

**Comment by svolence** [comment]
@websiteflash log有时候捕捉不到!手机端。网页端我都试过了！console控制台调试，和代码中写console.log也不行！

**Comment by websiteflash** [comment]
@svolence 配置的规则是否能够匹配你访问的页面地址？

**Comment by svolence** [comment]
@websiteflash fiddler其余tab都是正常的！配置的规则也是能够访问页面地址的！

**Comment by websiteflash** [comment]
@svolence 能把规则和地址发一下吗，我试一下

**Comment by websiteflash** [comment]
JsonViewer的问题，是安装包缺少JsonViewer.dll，我稍后更新下安装程序

**Comment by websiteflash** [comment]
@svolence 已经更新安装包，fix了JsonViewer的问题，感谢你的反馈

**Comment by svolence** [comment]
@websiteflash 我从新下载了一下！程序报错的问题！已经解决！同时我也找到了为什么log捕捉不到的原因了！
![111](https://cloud.githubusercontent.com/assets/4159479/6959394/15a9f6ee-d94b-11e4-8883-9bf5009b3659.jpg)
![image](https://cloud.githubusercontent.com/assets/4159479/6959399/21e7c9b8-d94b-11e4-9e87-19fb4dfd51fb.png)
![image](https://cloud.githubusercontent.com/assets/4159479/6959412/3906b3fc-d94b-11e4-8b88-961de4db8b2e.png)
以上这种情况下是正常的！
但是如果规则要是设置成host下的baidu.com的话，log日志就捕捉不到了
![image](https://cloud.githubusercontent.com/assets/4159479/6959456/cf5d4762-d94b-11e4-8158-4d3036c0a87e.png)
![image](https://cloud.githubusercontent.com/assets/4159479/6959459/d69d6660-d94b-11e4-818d-37d646bf7aa1.png)
![image](https://cloud.githubusercontent.com/assets/4159479/6959465/e6da1fbe-d94b-11e4-932a-6f650248b2bf.png)
谢谢你的耐心解答哈！！

**Comment by websiteflash** [comment]
@svolence 你的这个页面，host规则应该配tieba.baidu.com，可以在chrome控制台执行location.host，输出的结果就是Rosin匹配的host规则

**Comment by svolence** [comment]
@websiteflash 嗯！根据location.host定规则里面的host的比较准确，能捕捉到log! 问题关闭了哈！谢了！
