### ISSUE TITLE
安装完无法加载呢 fiddle4

### ISSUE THREAD

**Issue by a316574231** [AlloyTeam/Rosin#6]
安装完无法加载呢 fiddle4

![qq 20150605161712](https://cloud.githubusercontent.com/assets/4566393/8002127/d3fb9bf4-0b9e-11e5-820d-ea6b873ea3fc.png)

**Comment by kimphi** [comment]
我也是

**Comment by iazrael** [comment]
fiddler4需要下载for fiddler4的rosin, 两个版本对.net framework的版本要求不一样
你这里可能是装了for fiddler2的版本吧?
