### ISSUE TITLE
如下图，给rosin添加rule后，在log里找不到任何rule

### ISSUE THREAD

**Issue by lubeibi** [AlloyTeam/Rosin#7]
![qq 20150615170649](https://cloud.githubusercontent.com/assets/8043283/8156659/ef48f8fe-1380-11e5-8bb4-112533168461.png)
![qq 20150615170716](https://cloud.githubusercontent.com/assets/8043283/8156666/04f44a6e-1381-11e5-9734-d2a8abd37072.png)

**Comment by colorpeach** [comment]
我这边也是添加了rule后，log里找不到任何rule，是哪里出了问题？
